version: "3.7"

services:
  mongodb:
    image: mongo

  redisdb:
    image: redis:alpine

  portainer:
    image: portainer/portainer-ce

  sgpixels:
    image: ${DOCKER_REGISTRY-}sgpixels
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  mongo_data:
  portainer_data:
