version: "3.7"

services:
  mongodb:
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redisdb:
    container_name: redisdb
    restart: always
    ports:
      - "6379:6379"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  sgpixels:
    container_name: sgpixels
    command: "npm run start"
    environment:
      - NODE_ENV=development
      - DB_MONGO_HOST=mongodb://mongodb:27017/photos_db
    env_file:
      - ./server/.env.development
    depends_on:
      - mongodb
      - redisdb
    ports:
      - "8080:8080"
